#!/bin/sh -e

# Don't do anything when lo is configured.
if [ "$IFACE" = lo ]; then
        exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
        exit 0
fi

# Start script only when interface was correctly configured
if [ "$PHASE" != post-up ]; then
        exit 0
fi


# Work only when IPv4 enabled
if [ "$ADDRFAM" != inet ]; then
        exit 0
fi

# default configuration
DESTINATION_PORT="514"
SOURCE_PORT="6666"

SOURCE_INTERFACE=`/sbin/ip route show|grep default |awk '{print \$5}'`
SOURCE_IP=`/sbin/ip addr show dev $SOURCE_INTERFACE|grep -v inet6|grep inet|sed 's#/# #'|head -1 |awk '{print \$2}'`

# It is needed for got mac address, when it unknown
GATEWAY_IP=`/sbin/ip route | grep $SOURCE_INTERFACE | grep default | awk '{print \$3}'`

test -r /etc/default/netconsole && . /etc/default/netconsole

NAME="netconsole"

. /lib/lsb/init-functions


do_start() {
        echo "Starting $NAME: "
        if [ "$ENABLE_NETCONSOLE" = yes ]; then
        # load module
            if [ -z "$DESTINATION_SERVER_IP" ]; then
                log_failure_msg "Please set DESTINATION_SERVER_IP variable in /etc/default/netconsole or disable netconsole module"
                exit 1
            fi           
 
            # Encrease logging level up to 8, because standard debian has 7 and did not send many messagesg to netconsole
            # # https://www.kernel.org/doc/Documentation/sysctl/kernel.txt
            # standard debian squeeze:
            
            # sysctl -a|grep printk
            # squeeze: kernel.printk = 7   4   1   7
            # centos: kernel.printk = 6 4   1   7

            # If DESTINATION_SERVER_MAC is not defined explicitly we use gateway mac address
            if [ -z "$DESTINATION_SERVER_MAC" ]; then
                GATEWAY_MAC=`/usr/sbin/arping $GATEWAY_IP -c 5 -r -i $SOURCE_INTERFACE | tail -1`

                DESTINATION_SERVER_MAC=$GATEWAY_MAC
            fi

            MODULE_OPTIONS="netconsole=$SOURCE_PORT@$SOURCE_IP/$SOURCE_INTERFACE,$DESTINATION_PORT@$DESTINATION_SERVER_IP/$DESTINATION_SERVER_MAC"
 
            #/bin/dmesg -n 8  
            /sbin/modprobe "$NAME" "$MODULE_OPTIONS"
        else
                log_warning_msg "$NAME disabled in /etc/default/netconsole, if you need it, please enable"
        fi
}

do_start

exit 0

